#pragma once

// This header includes all files inside the framework project.
// It is meant for use by game projects ONLY.
// As new files are created, include them here so the game has easy access to them.
// It should not be included by any files inside the framework project.

#include "FrameworkPCH.h"

#include "Audio/AudioEngine.h"
#include "Audio/Channel.h"
#include "Components/Component.h"
#include "Components/ComponentManager.h"
#include "Components/ComponentRegistry.h"
#include "Components/AABBComponent.h"
#include "Components/AudioComponent.h"
#include "Components/AudioCueComponent.h"
#include "Components/CameraComponent.h"
#include "Components/CollisionComponent.h"
#include "Components/MeshComponent.h"
#include "Components/LuaScriptComponent.h"
#include "Components/LightComponent.h"
#include "Components/PointLightComponent.h"
#include "Components/SpotLightComponent.h"
#include "Components/DirectionalLightComponent.h"
#include "Components/ParticleEmitterComponent.h"
#include "Components/TransformComponent.h"
#include "Components/LightComponent.h"
#include "Core/GameCore.h"
#include "Core/FWCore.h"
#include "EventSystem/Event.h"
#include "EventSystem/EventManager.h"
#include "Gizmos/TransformGizmo3D.h"
#include "Lua/LuaGameState.h"
#include "Lua/LuaScript.h"
#include "Math/Vector.h"
#include "Objects/GameObject.h"
#include "Objects/Material.h"
#include "Objects/Mesh.h"
#include "Objects/ResourceManager.h"
#include "Objects/Sound.h"
#include "Objects/Texture.h"
#include "Particles/ParticleEmitter.h"
#include "Physics/PhysicsBody.h"
#include "Physics/PhysicsBody2D.h"
#include "Physics/PhysicsWorld.h"
#include "Physics/PhysicsWorld2D.h"
#include "Objects/AABB.h"
#include "Objects/MaterialEditor.h"
#include "Objects/TextureManager.h"
#include "Scene/Scene.h"
#include "UI/ImGuiManager.h"
#include "UI/ResourcesPanel.h"
#include "Utility/Color.h"
#include "Utility/FrameBufferObject.h"
#include "Utility/Helpers.h"
#include "Utility/JSONHelpers.h"
#include "Utility/ShaderProgram.h"
